clear

prefix  = [get_home_directory() '/.local/'];
eigendir = '/usr/include/eigen3';

# libdir = [prefix 'lib'];

mkoctfile(['-I' prefix 'include'],...
          ['-I' prefix 'include/opentrim'],...
          ['-I' eigendir],...
          ['-L' prefix 'lib'],...
          '-lopentrim',...
          ['-Wl,-rpath=' prefix 'lib'],...
          '-v','__opentrim_oct__.cpp')

mkoctfile(['-I' prefix 'include'],...
          ['-I' prefix 'include/opentrim'],...
          ['-I' eigendir],...
          ['-L' prefix 'lib'],...
          '-lxs_zbl',...
          ['-Wl,-rpath=' prefix 'lib'],...
          '-v','corteo_xs.cpp')


