# Print a concise summary of the CMake configuration
function(opentrim_print_var name)
  if(DEFINED ${name})
    message(STATUS "  ${name}: ${${name}}")
  else()
    message(STATUS "  ${name}: <not set>")
  endif()
endfunction()

message(STATUS "------------------------------------------------------")
message(STATUS "OpenTRIM CMake configuration summary")
message(STATUS "------------------------------------------------------")
opentrim_print_var(PROJECT_NAME)
opentrim_print_var(PROJECT_VERSION)
opentrim_print_var(PROJECT_DESCRIPTION)
opentrim_print_var(PROJECT_NAME_LOWERCASE)
opentrim_print_var(CMAKE_CXX_STANDARD)
if(DEFINED CMAKE_BUILD_TYPE)
  message(STATUS "  CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}")
else()
  message(STATUS "  CMAKE_BUILD_TYPE: <not set>")
endif()
opentrim_print_var(CMAKE_INSTALL_PREFIX)
opentrim_print_var(CMAKE_INSTALL_RPATH)
opentrim_print_var(OPENTRIM_BUILD_GUI)
opentrim_print_var(OPENTRIM_BUILD_TESTS)
opentrim_print_var(OPENTRIM_POST_BUILD_TESTS)

message(STATUS "Found dependencies:")

if(${Eigen3_FOUND})
  message(STATUS "  Eigen3:    ${Eigen3_VERSION}")
else()
  message(STATUS "  Eigen3:    <not found>")
endif()

if(${HDF5_FOUND})
  message(STATUS "  HDF5:      ${HDF5_VERSION}")
else()
  message(STATUS "  HDF5:      <not found>")
endif()

if(${libdedx_FOUND})
  message(STATUS "  libdedx:   ${libdedx_VERSION}")
else()
  message(STATUS "  libdedx:   <not found>")
endif()

if(OPENTRIM_BUILD_GUI)

  if(${Qt5_FOUND})
    message(STATUS "  Qt5:       ${Qt5_VERSION}")
  else()
    message(STATUS "  Qt5:       <not found>")
  endif()

  if(${Qwt_FOUND})
    message(STATUS "  Qwt:       ${QWT_VERSION_STRING}")
  else()
    message(STATUS "  Qwt:       <not found>")
  endif()

  if(${QtDataBrowser_FOUND})
    message(STATUS "  QtDataBrowser: ${QtDataBrowser_VERSION}")
  else()
    message(STATUS "  QtDataBrowser: <not found>")
  endif()

endif()

message(STATUS "------------------------------------------------------")